### PR TITLE
Introduced API to allow for extending RedisClusterClient and its connections

### PR DESCRIPTION
**Pull request by jruaux**
Feature request: #1754

### CODE REVIEW

**Review by sokomishalov — APPROVED** [review]
LGTM

**Comment by mp911de** [comment]
The changes generally look fine. @jruaux do you plan on adding more commits or do you consider this PR complete?

**Comment by jruaux** [comment]
I don't plan on adding any more commits. The PR is complete.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Pull request merged**
