### PR TITLE
reformat getEventConstructor for JfrEventRecorder not to synchronize for each read

### PR DESCRIPTION
**Pull request by HashZhang**
As stated in the topic.

### CODE REVIEW

**Review by sokomishalov — APPROVED** [review]
LGTM

**Comment by mp911de** [comment]
`constructorMap` is not thread-safe and a `map.get(…)` requires external synchronization as per `HashMap` Javadoc. What is the motivation behind this change?

**Comment by HashZhang** [comment]
I want to remove the synchronization whenever there is an Event. I think we can change it to ConcurrentHashMap.

**Comment by mp911de** [comment]
I see. `ConcurrentHashMap` has much more complex locking mechanisms that are activated upon each retrieval. We have a limited amount of event types, so after a while, the `Map` is going to contain all types and we are no longer writing concurrently to `JfrEventRecorder.constructorMap`. I would like to keep things as they are as for the general performance behavior simpler maps are much more efficient. 

One other optimization could be turning `constructorMap` into `volatile` and replace the map upon write and remove `synchronized` entirely.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Pull request closed without merging**
