### PR TITLE
refactor: simplify condition to invoke "resolveCodec" method in AnnotationRedisCodecResolver

### LINKED ISSUE #1149: refactor simplify condition to invoke "resolveCodec" method in AnnotationRedisCodecResolver
While going through the `AnnotationRedisCodecResolver.java` class, I noticed that this condition 

https://github.com/lettuce-io/lettuce-core/blob/c98108dd7fbe9bee8702e468efff4b085a976374/src/main/java/io/lettuce/core/dynamic/codec/AnnotationRedisCodecResolver.java#L73-L76 can be improved. I have a refactor in place and I am preparing a PR.

### PR DESCRIPTION
**Pull request by machi1990**
Fixes #1149

### CODE REVIEW

**Comment by mp911de** [comment]
I'm not sure the change really improves and helps with expressiveness. It makes sense to have the test case. Regarding the conditionals, it would rather make sense introducing a new method along the lines of `hasAtMostOne(Collection<?>)` instead of pushing the condition into the method body of `resolveCodec`

**Comment by machi1990** [comment]
> I'm not sure the change really improves and helps with expressiveness. It makes sense to have the test case. Regarding the conditionals, it would rather make sense introducing a new method along the lines of `hasAtMostOne(Collection<?>)` instead of pushing the condition into the method body of `resolveCodec`

Thanks for the review. I'll update the PR later on.

**Comment by mp911de** [comment]
Thanks a lot, that's merged and polished now.

**Comment by machi1990** [comment]
> Thanks a lot, that's merged and polished now.

Great thanks for the feedbacks too.

**Pull request closed without merging**
