### PR TITLE
Some kotlin api generator fixes

### LINKED ISSUE #1415: Update Kotlin API generator to remove implementation generators

### PR DESCRIPTION
**Pull request by SokoMishaLov**
https://github.com/lettuce-io/lettuce-core/issues/1414
https://github.com/lettuce-io/lettuce-core/issues/1415
https://github.com/lettuce-io/lettuce-core/issues/1416
And other fixes to the generator to provide the correct current API.
Also, it is unnecessary to mark flow methods with `suspend` modifier.

P.S. btw I think maybe it makes sense to reconsider naming conventions for classes and rename all from "Suspendable" to "Coroutines" due to the existence of flow and non-suspendable methods and to unify API, but I would not edit it until your approval on that

### CODE REVIEW

**Comment by mp911de** [comment]
Can you remove the changes in the `…Commands.kt` files? I merged an earlier PR that now causes some incompatibilities.

>  btw I think maybe it makes sense to reconsider naming conventions for classes and rename all from "Suspendable" to "Coroutines" due to the existence of flow and non-suspendable methods and to unify API, but I would not edit it until your approval on that

I'm fine with renaming from `…Suspendable…` to `…Coroutines…` in a separate PR. However, let's do this as manual task since the API generator still generates things that would not compile or do not match the types we have right now. There are a few tweaks we need to apply to the generator before we can rely on the generated source.

Care to rebase your PR?

**Comment by SokoMishaLov** [comment]
Not a big deal, rebased.
Well, I think some changes of `Commands` should stay because this pr is about to fix more issues for both generator and resulting API, like:
1) Removed unnecessary `suspend` modifiers in flow methods
2) Added `Any` bound to command type params for asFlow() methods
3) Replaced `collectList().awaitFirstOrNull()` with `asFlow().toList()` for collections to avoid useless nullability
4) Other nullability issues
5) Some API clean up - removed explicit Unit types and added kotlin property access for getters
6) Documentation fixes - {@code *} -> `*`, {@link *} -> [*], license years

**Comment by mp911de** [comment]
Thanks a lot for spending some time on this topic. You're right, it makes sense to include these changes before going GA. I was hoping to get the GA release done today or tomorrow, but these changes require a bit more of thought since we need to go over the entire API surface again. Ideally, we can include also some `Flow` changes where we expect responses from large data structures. Not so much `SLOWLOG` or `COMMANDS`, more `HGETALL`, `ZRANGE` and so on.

**Comment by SokoMishaLov** [comment]
You are welcome!
About Flows for large data structures - I propose such a solution (example for `hgetall`)
https://github.com/SokoMishaLov/lettuce-core/commit/fb4090572407c180a6b454afaa2f304006266249

**Comment by mp911de** [comment]
For `Flow` we can simply bridge `Publisher` as that works pretty well already. I'm not keen on introducing another concept to stream data. `StreamingChannel`s are somewhat okay for async/sync usage, for reactive and coroutines `Publisher` respective `Flow` are the way to go.

**Comment by SokoMishaLov** [comment]
Fair enough, but here is a thing - current underlying reactive implementation "eagerly" collects data (with either MapOutput or *ScanOutput) for some commands that should be `Flow`-friendly (like mentioned before `HGETALL`, `HSCAN`) and returns it back in `Mono`.  And yes, it's quite simple to convert this `Mono<Map<K, V>>` to `Flow<Map<K, V>>` which contains 1 element, but it seems not very efficient actually.

**Comment by mp911de** [comment]
You're right with `MapOutput` when used in `hgetall` (that's what I stumbled upon and going to address with #1434). I'm planning to change the reactive API from `Mono<Map>` to `Flux<KeyValue>` to use `KeyValueListOutput` as output.

`HSCAN` shouldn't be an issue since it's built for batching anyway (by the way, it would make sense to create a scan utility for coroutines similar to `ScanStream`/`ScanIterator`, #1435).

We have a few streaming-enabled outputs such as `KeyListOutput` that can be either used in aggregation mode or streaming mode, depending on the Lettuce `Subscriber` (defaults to `ListSubscriber.instance()` but can also be backed by `RedisSubscription` which is the actual `Subscription` interface implementation.

Let me finish the round of polishing so you can review my changes.

**Comment by SokoMishaLov** [comment]
Sure, sounds good.
I've investigated a bit of how `HGETALL` for `Flow`-based variant could look like
https://github.com/SokoMishaLov/lettuce-core/commit/ff4c261112c654a9a637c3b9eb2f595e5eef9597

**Comment by mp911de** [comment]
We can tweak `KeyValueListOutput` to read `key` from the command response instead from a provided `Iterable` which simplifies the implementation a bit.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished. The `HGETALL` change is at 52ae9c0c246457881726ac6466fdb9fcc04f901f.

**Comment by mp911de** [comment]
Final thought: Do you want to handle the `suspendable` to `coroutine` renaming or should I take care of it?

**Comment by SokoMishaLov** [comment]
Nice!
I could do it tomorrow. But of course, if you're in a hurry with GA you could take care of it.

**Pull request closed without merging**
