### PR TITLE
5.1.x

### PR DESCRIPTION
**Pull request by xjs1919**
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [ ] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [ ] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/master/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks. Mind to have a look on the breaking tests?

**Comment by xjs1919** [comment]
all the junit tests are passed，but i have no idea about the following errors： 

lzf_d.c:57:9: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
         ^
    CC pqsort.o
    CC zipmap.o
    CC sha1.o
    CC ziplist.o
    CC release.o
    CC networking.o
    CC util.o
    CC object.o
object.c: In function ‘memoryCommand’:
object.c:1444:9: error: expected ‘;’ before ‘sdsfree’
         sdsfree(info);
         ^
Makefile:248: recipe for target 'object.o' failed

**Comment by mp911de** [comment]
The build failure you mentioned originate likely in Redis changes in the `unstable` branch. The other builds for 3.x, 4.x and 5.x branches are green.

**Comment by mp911de** [comment]
Thanks a lot, that's merged and polished now.

**Pull request closed without merging**
