### PR TITLE
Allow client to pick a specific TLS version and introduce PEM-based configuration

### PR DESCRIPTION
**Pull request by amohtashami12307**
Valid protocols "TLSv1", TLSv1.1", "TLSv1.2"

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [x] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/master/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

**Comment by amohtashami12307** [comment]
Thank you for the quick response. Yes agreed. What other low-level interfaces were you referring to? like allowing the user to pick their desired cipher suits or in other words are there other things you would like to see?

**Comment by mp911de** [comment]
Basically, all the things that are possible with `SslContextBuilder` or `SslContext`. Certificates, key and trustmanager factories, various protocol levels. SSL config can be tricky, so there is probably no one-fits-all.

**Comment by amohtashami12307** [comment]
I have moved the SSLParamaters's protocols and ciphersuites into ssloptions. @mp911de could you please review this and let me know what you think ?

**Comment by mp911de** [comment]
I will have a look next week. Thanks a lot!

**Comment by amohtashami12307** [comment]
Okay sounds good. Happy Thanks giving.

**Comment by amohtashami12307** [comment]
Hi @mp911de, are there any update on this ?

**Comment by mp911de** [comment]
It will take me a bit more time until I get to this.

**Comment by mp911de** [comment]
I took a look and configuring ciphers and protocols makes sense. I will take this PR from here to polish it (e.g. use varargs instead of `String` and `String[]` overloads) and add PEM-based certificate options.

I would also like to move `SslContextBuilder` and `SSLParameters` creations into `SslOptions`.

**Comment by mp911de** [comment]
Thanks a lot. That's squashed, merged and polished for 5.3.0. I also added a configuration option for PEM-based keys and certificates.

**Pull request closed without merging**
