### PR TITLE
Read from random slave preferred

### PR DESCRIPTION
**Pull request by petetanton**
I would like to be able to load balance read replicas to avoid overwhelming a particularly fast replica. With the ReadFromSlavePreferred class, I found that one or two nodes would end up taking the vast majority of the traffic whilst other nodes are doing very little work.

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks for your pull request. Workload distribution depends on three factors when looking at slave/slave-preferred mechanisms:

1. Response time of nodes
2. The selected node (derives from response time as `Nodes` contains nodes ordered by response time)
3. Caching (Cluster client selects a node once and caches the result until topology refresh)

In general, there is a primary decision, whether the actual node list should be sorted or random in general. It looks to me as this should be the bit where we look into as we could:

1. Reuse existing `ReadFrom` settings without the need to create new ones
2. Skip the `PING` roundtrip to determine response times
3. Shuffle nodes beforehand

WDYT?

**Comment by petetanton** [comment]
Sorry for my slow response.

Ideally, I would prefer a random list as this will ensure equal traffic between each read node.
It would be good to keep the PING as this will verify that the nodes are actually avaliable however there would be no need to measure the latency.
Any thoughts?

**Comment by mp911de** [comment]
I'm fine with keeping `PING`. I think I would add two options:

1. Option to disable sort by latency
2. Option to enable randomizing

There are no common configuration bits between Redis Cluster and Master/Slave right now and I'd like to keep Master/Slave fairly simple, without additional configuration options. Therefore, I'd introduce system properties that allow configuration without introducing config API in the first place.

**Comment by mp911de** [comment]
I added configuration options via System properties to Lettuce 4.5 and 5.1:

```
-Dio.lettuce.core.topology.sort=BY_LATENCY (default)
-Dio.lettuce.core.topology.sort=NONE (leave nodes as they were reported by Redis)
-Dio.lettuce.core.topology.sort=RANDOMIZE (shuffle nodes)
```

Closed via 2138dc6 and 90103db, snapshot builds are available via OSS Sonatype.

**Comment by adityak93** [comment]
For people stumbling here from google search (like me 2 weeks ago), please do check: https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-elasticache-launches-reader-endpoint-for-redis/ for balancing load among read replicas. this was recently introduced by AWS (June 19)

**Pull request closed without merging**
