### PR TITLE
Add anyReplica setting for ReadFrom

### PR DESCRIPTION
**Pull request by omer-cilingir**
A ReadFrom setting for reading from only all replicas

### CODE REVIEW

**Comment by mp911de** [comment]
Care to elaborate on why `ReadFrom.ANY` isn't sufficient?

**Comment by omer-cilingir** [comment]
Sorry for not explanation,
All the write commands go to the master node, the master is already busy and has high CPU usage, so the get commands go to only the replicas, so we can distribute the load & CPU usage.
This setting may be useful for applications whose the write is half the read.

**Comment by mp911de** [comment]
Thanks a lot. From that perspective, it makes sense to add another constant.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Pull request closed without merging**
