### PR TITLE
Flaky test fix and allow all commands in pubsub mode in resp3

### PR DESCRIPTION
**Pull request by sancar**
This pr allows all commands to work in resp3 not only allowed ones in resp2(pub/sub/ping .. etc)

Instead of doing the check locally on the client side, I have decided to rely on the server for correct behavior for code simplicity. Because otherwise, we need to check resp2/3 on the client side and make the behavior different.

Note that this investigation started with PubSubCommandTest#pingNotAllowedInSubscriptionState failing against our redis server test in Upstash(https://upstash.com/). Further investigation revealed that there is a bug in deciding if the connection is subscribed or not.

The bug can be reproduced easily by putting a sleep for 10 seconds in PubSubCommandHandler#notifyPushListeners right before do  `notifyMessage`.

The problem seems to be the future for subscribe is completed after we are updating the internal state of PubsubEndpoint(adding a new channel to the channels set). Because of that, in some unlucky timing, the test (PubSubCommandHandler#notifyPushListeners) fails.

1. subscribe future is completed.
2. new channel is not put into the channels map in PubsubEndpoint
3. Test continues to send an echo to the server.
4. Client side for PubSubEndpint#isSubscribed returns false because channels and patterns are empty.
5. Server runs the command and does not return an error because the client is talking with resp3 and all commands are allowed.
6. Even if we were talking in resp2 test would fail because of the error message of the exception.

With this change, the exception type is changed from RedisException to RedisCommandException(which extends RedisException) so it should be OK from API backward compatibility standpoint. If it is not expected to be the same.

So this is a Friday work, starting with a flaky test and ending with code simplification and fixing resp3 behavior. I hope I did not delete too much code.

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [x] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/main/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

**Comment by sancar** [comment]
I haven't created a feature request because this is mostly a bug fix. But I can create one if requested.

**Comment by mp911de** [comment]
This code was in place because of a reason and just wiping everything isn't going to work. RESP3 indeed provides much more freedom, however Lettuce can also run against RESP2 and we need safe guards in place to avoid invalid protocol usage. We can consider a refinement if the protocol version was checked in the code.

**Comment by sancar** [comment]
> we need safe guards in place to avoid invalid protocol usage

What would be the problem ? When Lettuce used with resp2 together with invalid commands under subscribe, the server will return the error anyway. Can you help me understand what is the downside of removing client-side checks?

**Comment by mp911de** [comment]
Please follow the changes around https://github.com/lettuce-io/lettuce-core/issues/579.

**Comment by sancar** [comment]
@mp911de Ok, I got the problem. Thanks for sharing the related changes. 
I am closing this pr but leaving the issue open as it needs an alternatif fix. 
I have updated the description of the issue accordingly. 
FYI, I may work on a alternative solution when I have time but can not promise to work on these days.

**Pull request closed without merging**
