### PR TITLE
Add GEOSEARCH to read-only commands #2568

### PR DESCRIPTION
**Pull request by kajte**
Solves https://github.com/lettuce-io/lettuce-core/issues/2568

Set GEOSEARCH as read-only command to allow running the command on replicas. Works similar to https://github.com/lettuce-io/lettuce-core/pull/2198.

### CODE REVIEW

**Comment by thx01138** [comment]
@mp911de @dengliming Can this PR be merged? I want to add another PR just like this to support FCALL_RO but since the unit test for this counts number of commands in the read only list, I want to open my PR after this is merged to main.

**Comment by thx01138** [comment]
@mp911de Is this ready to merge? Would you do the honors?

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Comment by kajte** [comment]
> Thank you for your contribution. That's merged, polished, and backported now.

Awesome! Thanks for you too!

**Pull request closed without merging**
