### PR TITLE
bump netty version to address security vulnerability

### PR DESCRIPTION
**Pull request by YoloZoloo**
This is to use the latest netty version that fixed the security vulnerability in netty packages. 
Having a new release with the latest netty package would be very helpful. Thank you very much.

The security vulnerability report: https://github.com/netty/netty/security/advisories/GHSA-6mjq-h674-j845
 

Make sure that:

- [X] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [ ] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [X] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/main/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [X] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

**Comment by YoloZoloo** [comment]
Any updates/ideas on this issue?

**Comment by mp911de** [comment]
We're always happy to bump versions if we happen to ship a new release. Generally, we avoid pull requests for version increments. Additionally:

1. We do not use `SniHandler` because we do not run a server
2. If you bump the dependency version in your pom/gradle-file, then your project doesn't pull in a netty version with known vulnerabilities.

**Comment by YoloZoloo** [comment]
Understandable. Yes, this is not an immediate security vulnerability. But it is nicer to pay attention to issues found in security scans.
For now, overriding netty-handler dependency can do the workaround. Having a lettuce release with the latest dependencies would be even better. Do you have any ETA on the next release?

**Comment by YoloZoloo** [comment]
@mp911de I would really appreciate it if you could give any estimation of the next release.
Since my questions were answered I will close down this PR.

**Comment by mp911de** [comment]
I scheduled the release for Jul 12.

**Pull request closed without merging**
