### PR TITLE
Support for ACL commands #1538

### PR DESCRIPTION
**Pull request by sokomishalov**
Draft PR for ACL commands API.
My main concern - should we provide higher abstractions for rules?

### CODE REVIEW

**Comment by mp911de** [comment]
Good first draft. Let's move `AclCategory` into an `api` package so we don't depend on the `model` package.

Can we also make the `username` a `String` instead of using the keytype `K`?

**Comment by mp911de** [comment]
In preparation for Lettuce 6.1 M1, I'd like to move this change to M2.

**Comment by sokomishalov** [comment]
I've made some fixes according to the first review

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now. I removed `UserRulesOutput` because it didn't consider nested lists. We could introduce a parser for `List<Object>` that creates an user object and that can be translated into `ACL SET USER` args.

**Pull request closed without merging**
